"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-eayeo+rlpnk!89%yb9c*v_(5xt6hsgw4(lqsrom(bkes^l7p2e"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "finance_app",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.kakao",
    "allauth.socialaccount.providers.naver",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "finance_app.context_processors.scheduler_status",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth Settings
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_EMAIL_VERIFICATION = "none"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        }
    },
    "github": {
        "APP": {
            "client_id": os.getenv("GITHUB_CLIENT_ID", ""),
            "secret": os.getenv("GITHUB_CLIENT_SECRET", ""),
            "key": "",
        }
    },
    "kakao": {
        "APP": {
            "client_id": os.getenv("KAKAO_CLIENT_ID", ""),
            "secret": os.getenv("KAKAO_CLIENT_SECRET", ""),
            "key": "",
        }
    },
    "naver": {
        "APP": {
            "client_id": os.getenv("NAVER_CLIENT_ID", ""),
            "secret": os.getenv("NAVER_CLIENT_SECRET", ""),
            "key": "",
        }
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "debug_allauth.log",
        },
    },
    "loggers": {
        "allauth": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "request": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# Social Account Provider specific settings
SOCIALACCOUNT_PROVIDERS["kakao"]["SCOPE"] = ["profile_nickname"]
SOCIALACCOUNT_PROVIDERS["google"]["SCOPE"] = ["profile", "email"]
SOCIALACCOUNT_PROVIDERS["naver"]["SCOPE"] = ["name"]
SOCIALACCOUNT_PROVIDERS["github"]["SCOPE"] = ["user:email", "read:user"]

# To populate user models from provider
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"

# ─────────────────────────────────────────────────────────────────────────────
# Celery + Redis 비동기 작업 큐 설정
# ─────────────────────────────────────────────────────────────────────────────
# 수정 전: REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
# 수정 후: Windows 환경에서 IPv6 충돌을 방지하기 위해 127.0.0.1을 기본값으로 지정합니다.
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")

# 브로커: Redis (작업을 큐에 넣는 역할)
CELERY_BROKER_URL = REDIS_URL

# 결과 백엔드: Redis (완료된 태스크 결과 저장)
CELERY_RESULT_BACKEND = REDIS_URL

# 직렬화 설정 (JSON이 Pickle보다 안전)
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# 타임존
CELERY_TIMEZONE = TIME_ZONE

# 태스크 결과 보관 시간: 1시간 (3600초)
CELERY_RESULT_EXPIRES = 3600

# 태스크 실패 시 재시도 설정
CELERY_TASK_ACKS_LATE = True  # 태스크 완료 후 ack (장애 시 재처리 보장)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 무거운 태스크 대비 한 번에 1개만 prefetch

# 태스크 라우팅 (무거운 태스크는 heavy 큐, 빠른 건 default 큐)
CELERY_TASK_ROUTES = {
    "finance_app.tasks.orchestrate_report_pipeline": {"queue": "heavy"},
    "finance_app.tasks.generate_report_task": {"queue": "heavy"},
    "finance_app.tasks.generate_comparison_report_task": {"queue": "heavy"},
    "finance_app.tasks.generate_charts_for_ticker_task": {"queue": "default"},
}

# Worker Pool 설정 (OS 자동 감지)
# - Windows: prefork 미지원 → threads 필수
# - macOS:   prefork가 SIGSEGV 충돌 → threads 사용
# - Linux:   prefork 정상 작동, 배포 환경에서 성능 우수
import platform

_os_name = platform.system()  # "Windows", "Darwin"(macOS), "Linux"

if _os_name == "Linux":
    CELERY_WORKER_POOL = "prefork"  # Linux 배포 서버: 가장 효율적
    CELERY_WORKER_CONCURRENCY = 4
else:
    CELERY_WORKER_POOL = "threads"  # Windows / macOS: 안전한 스레드 모드
    CELERY_WORKER_CONCURRENCY = 4
