# Generated by Django 5.2.11 on 2026-02-27 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="alert_threshold_percent",
            field=models.FloatField(default=5.0, help_text="상하락 알림 임계값(%)"),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        blank=True, help_text="관련 티커", max_length=10, null=True
                    ),
                ),
                ("title", models.CharField(help_text="알림 제목", max_length=200)),
                ("message", models.TextField(help_text="알림 상세 내용")),
                (
                    "notification_type",
                    models.CharField(
                        default="price_alert",
                        help_text="알림 유형 (예: price_alert, news)",
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False, help_text="읽음 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
